#!/usr/bin/env python3
"""Generate the in-memory Swift payload for bundled media attributions."""

from __future__ import annotations

import argparse
import base64
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "YouNew/Resources/MediaAttributions.json"
OUTPUT = ROOT / "YouNew/Data/GeneratedMediaAttributions.swift"


def rendered_source() -> str:
    records = json.loads(SOURCE.read_text(encoding="utf-8"))
    canonical = json.dumps(records, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    encoded = base64.b64encode(canonical).decode("ascii")
    lines = "\n".join(
        f"        {encoded[index : index + 100]}"
        for index in range(0, len(encoded), 100)
    )
    return f"""// Generated by scripts/generate-media-attributions-swift.py.
// Do not edit by hand; update YouNew/Resources/MediaAttributions.json and regenerate.

import Foundation

enum GeneratedMediaAttributions {{
    static let base64JSON = \"\"\"
{lines}
    \"\"\"
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail when generated Swift is stale.")
    args = parser.parse_args()

    expected = rendered_source()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"Generated media attribution payload is stale: {OUTPUT.relative_to(ROOT)}")
            return 1
        print("Generated media attribution payload is current")
        return 0

    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
