insert into public.categories (title, slug, short_description, status, priority)
values
  ('Housing', 'housing', 'Renting, housing support and tenant rights.', 'draft', 10),
  ('Work', 'work', 'Jobs, employment contracts, pay and workplace rights.', 'draft', 20),
  ('Documents', 'documents', 'BSN, BRP, DigiD and residence documents.', 'draft', 30),
  ('Healthcare', 'healthcare', 'GPs, hospitals, pharmacies and health insurance.', 'draft', 40),
  ('Education', 'education', 'Schools, vocational and higher education.', 'draft', 50),
  ('Language learning', 'language-learning', 'Dutch courses, NT2 and language support.', 'draft', 60),
  ('Government', 'government', 'National government services and authorities.', 'draft', 70),
  ('Banking', 'banking', 'Bank accounts, payments and financial-service routes.', 'draft', 80),
  ('Taxes', 'taxes', 'Tax returns, assessments and Tax Administration routes.', 'draft', 90),
  ('Benefits', 'benefits', 'Housing, healthcare, childcare and child benefits.', 'draft', 100),
  ('SIM & telecom', 'sim-telecom', 'SIM cards, mobile subscriptions and telecom rights.', 'draft', 110),
  ('Internet', 'internet', 'Home internet, installation and provider switching.', 'draft', 120),
  ('Utilities', 'utilities', 'Energy, water, meters and utility contracts.', 'draft', 130),
  ('Transport', 'transport', 'Public transport, cycling, driving and parking.', 'draft', 140),
  ('Rules', 'rules', 'National and municipal rules and permits.', 'draft', 150),
  ('Fines', 'fines', 'Traffic, parking and waste fines and objections.', 'draft', 160),
  ('Legal help', 'legal-help', 'Legal information, advice and representation routes.', 'draft', 170),
  ('Family', 'family', 'Family records, relationships and family migration.', 'draft', 180),
  ('Children', 'children', 'Birth, childcare, school and youth services.', 'draft', 190),
  ('Safety', 'safety', 'Police, crime reports, scams and domestic safety.', 'draft', 200),
  ('Emergency', 'emergency', 'Immediate danger and verified emergency routes.', 'draft', 210),
  ('Shopping', 'shopping', 'Consumer rights, returns and warranties.', 'draft', 220),
  ('Daily life', 'daily-life', 'Practical everyday services and routines.', 'draft', 230),
  ('Pets', 'pets', 'Registration, veterinary care and local pet rules.', 'draft', 240),
  ('Business', 'business', 'Starting and operating a business.', 'draft', 250),
  ('Integration', 'integration', 'Civic integration duties, routes and exams.', 'draft', 260),
  ('Municipal services', 'municipal-services', 'Registration, moving and local public services.', 'draft', 270)
on conflict (slug) do nothing;
